blank_issues_enabled: false

contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/Trivedram/.github/discussions
    about: Ask questions, share ideas, or start a discussion.

  - name: 📖 Documentation
    url: https://github.com/Trivedram
    about: Read the documentation before opening an issue.